--
-- You can add SQL code here
-- The code is executed at the end of each deploy process
--
-- [NOTE] Use "IF NOT EXISTS" and "ON CONFLICT" to have the code executed once
-- i.e. "CREATE TABLE IF NOT EXISTS xxxxx" and "INSERT () ON CONFLICT DO NOTHING"
--